---
title: "Homework 6"
output:
  pdf_document: default
  html_document: default
Author: Aji John
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 21



```{r,include=TRUE}
Xt_1 <- 1
sim.a <- function(n=100,phi=0.9,theta=0.99)
{
  Zt <- rnorm(n+3,sd = 1)
  phi*Xt_1 + Zt[4:(n+3)] + theta*Zt[1:n]
}


set.seed(42)

acf(sim.a(), lag.max=20, plot=TRUE)
```



```{r,include=FALSE}
#With σ2 = 1 and φ = 0.9, plot the ACF (note: not the ACVF!) at lags h = 0,1,...,20 for θ set to 0.99, 0, −0.25, −0.5, −0.75 #and, finally, −0.99. Comment briefly on how these compare with the ACVFs shown in overheads IX–6, IX–8, IX–9, IX–10, IX–11 #and IX–13 for an ARMA(1,1) process with similar settings for σ2, φ and θ.
phi<-0.9
theta<-0.99
sigma_q<-1

h<- 1
gamma_0 <- sigma_q^2 * ((1+theta^2)+ 2 * theta*phi^3)/(1-phi^2)

gamma_1 <- sigma_q^2  * ((1+theta^2)*phi +  theta*phi^(2) + +  theta*phi^(4))/(1-phi^2)
gamma_2 <- sigma_q^2  * ((1+theta^2)*phi^2 +  theta*phi + +  theta*phi^(5))/(1-phi^2)

gamma_h <- sigma_q^2 *  ((1+theta^2)*phi^h +  theta*phi^(h+3) + +  theta*phi^(h-3))/(1-phi^2)
```
