---
title: "Homework 5"
output:
  pdf_document: default
  html_document: default
Author: Aji John
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 14 b



```{r,include=FALSE}
sim.a <- function(n=100,a=-2,b=1,c=pi/4)
{
  Zt <- rnorm(n+2)
  a + b*Zt[3:(n+2)] + c*Zt[1:n]
}

sim.b <- function(n=100,a=-3,b=1,c=pi/4)
{
  Zt <- rnorm(n+2,sd=4)
  a + b*Zt[3:(n+2)] + c*Zt[1:n]
}

set.seed(42)
tss <- sim.a()
plot(tss,col="blue",xlab="t",typ="b", ylab=expression(x[t]))


plot.ACVFbiasedVSunbiased <- function(ts, main=NULL,ylims=c(-2,4))
{
    n <- length(ts)
    xs <- 0:(n-1)
    ys <- acf(ts, lag.max=n-1, type="covariance", plot=FALSE)$acf
    plot(xs,ys,typ="p",xlab="h  (lag)",ylab="ACVF",ylim=ylims,col="blue",main=main)
    points(xs,ys*n/(n-(0:(n-1))),pch="*",col="red")
    abline(h=0,lty="dashed")
    abline(h=max(ys),lty="dotted")
}

### overhead VI-11

plot.ACVFbiasedVSunbiased(tss,"Biased & Unbiased Sample ACVF for Xt")

```

## Problem 14 b


```{r,include=FALSE}

acf.xt.ts <- acf(tss, lag.max=4, plot=TRUE)$acf


```

```{r,include=FALSE}

dup.row<-function(x,n){
   matrix(rep(x,each=n),nrow=n)
}
dup.col <-function(x,n){
   matrix(rep(x,each=n), ncol=n, byrow=TRUE)
}

```

```{r,include=FALSE}

#create matrix from vectors
M <- cbind(tss)
#cov(M)



k <- ncol(M) #number of variables
n <- nrow(M) #number of subjects
 
#create means for each column
M_mean <- matrix(data=1, nrow=n) %*% cbind(mean(tss)) 
 
#creates a difference matrix
D <- M - M_mean
 
#creates the covariance matrix
C <- (n-1)^-1* t(D) %*% D
```


```{r,include=FALSE}

#create matrix from vectors
as.vector(acf(tss, lag.max=4, plot=TRUE)$acf[2:5])

acf.tss.1 <- as.vector(acf(sim.a(), lag.max=4, plot=TRUE)$acf[2:5])
acf.tss.2 <- as.vector(acf(sim.a(), lag.max=4, plot=TRUE)$acf[2:5])
acf.tss.3 <- as.vector(acf(sim.a(), lag.max=4, plot=TRUE)$acf[2:5])
acf.tss.4 <- as.vector(acf(sim.a(), lag.max=4, plot=TRUE)$acf[2:5])

acf.tss.mat <- as.matrix(rbind(acf.tss.1,acf.tss.2,acf.tss.3,acf.tss.4))


df <- data.frame()

for (k in 1:1000){
  
  row_i <-  as.vector(acf(sim.a(), lag.max=4, plot=FALSE)$acf[2:5])
  df <- rbind(df,row_i)
}

acf.tss.mat.1000 <- as.matrix(df)
colnames(acf.tss.mat.1000) <- c('rho_1','rho_2','rho_3', 'rho_4')

df_corr <- data.frame()

for (i in 1:4){
 b <- c()

 for (j in 1:4)
 {
   b <- c(b, cor(acf.tss.mat.1000[,i],acf.tss.mat.1000[,j]))  
 }
 df_corr <- rbind(df_corr,b)
}

df_cov <- data.frame()

for (i in 1:4){
 b <- c()

 for (j in 1:4)
 {
   b <- c(b, cov(acf.tss.mat.1000[,i],acf.tss.mat.1000[,j]))  
 }
 df_cov <- rbind(df_cov,b)
}
 colnames(df_corr) <-  c('cor_1','cor_2','cor_3', 'cor_4')
 colnames(df_cov) <-  c('cov_1','cov_2','cov_3', 'cov_4')

```

## Sample mean
```{r}

#knitr::kable(colMeans(acf.tss.mat.1000))

```
## Correlation Matrix
```{r}

knitr::kable(df_corr)

```

## Covariance Matrix
```{r}

knitr::kable(df_cov)

```

### It is very much in sync with what large sample theory suggests



# Changing the value , a = -2, sd =4

```{r,include=FALSE}

#create matrix from vectors
set.seed(42)
df2 <- data.frame()

for (k in 1:1000){
  
  row_i <-  as.vector(acf(sim.b(), lag.max=4, plot=FALSE)$acf[2:5])
  df2<- rbind(df2,row_i)
}

acf.tss.mat.1000.v2 <- as.matrix(df2)
colnames(acf.tss.mat.1000.v2) <- c('rho_1_2','rho_2_2','rho_3_2', 'rho_4_2')

df_corr_2 <- data.frame()

for (i in 1:4){
 b <- c()

 for (j in 1:4)
 {
   b <- c(b, cor(acf.tss.mat.1000.v2[,i],acf.tss.mat.1000.v2[,j]))  
 }
 df_corr_2 <- rbind(df_corr_2,b)
}

df_cov_2 <- data.frame()

for (i in 1:4){
 b <- c()

 for (j in 1:4)
 {
   b <- c(b, cov(acf.tss.mat.1000.v2[,i],acf.tss.mat.1000.v2[,j]))  
 }
 df_cov_2 <- rbind(df_cov_2,b)
}
 colnames(df_corr_2) <-  c('cor_1','cor_2','cor_3', 'cor_4')
 colnames(df_cov_2) <-  c('cov_1','cov_2','cov_3', 'cov_4')

```

## Covariance Matrix 2
```{r}

knitr::kable(df_cov_2)

```


